/* Generated by model/kws/export.py. Do not edit.
   Regenerate with: python -m kws.export --checkpoint <run>/checkpoint.pt */

#pragma once

#include <stdint.h>

#include "kws_layer.h"

#define KWS_NUM_LAYERS      10
#define KWS_NUM_CLASSES     12
#define KWS_INPUT_FRAMES    49
#define KWS_INPUT_MFCC      10
#define KWS_MODEL_CHANNELS  64

/* Largest activation tensor in elements, sizes the two ping pong arenas. */
#define KWS_MAX_TENSOR_ELEMS 8000

extern const kws_layer_t kws_layers[KWS_NUM_LAYERS];
extern const char *const kws_labels[KWS_NUM_CLASSES];

/* Quantisation of the feature grid handed to layer 0. */
extern const float   kws_input_scale;
extern const int32_t kws_input_zero_point;

/* Per coefficient feature standardisation, applied before quantisation. */
extern const float kws_feature_mean[KWS_INPUT_MFCC];
extern const float kws_feature_std[KWS_INPUT_MFCC];
