/* Generated by model/kws/export.py. Do not edit.
   Regenerate with: python -m kws.export --checkpoint <run>/checkpoint.pt */

#pragma once

#include "mfcc_config.h"

/* Window is applied to one 480 sample frame before the transform. */
extern const float mfcc_window[480];

/* Row major, 40 mel bands by 257 spectrum bins. */
extern const float mfcc_filterbank[10280];

/* Row major, 10 coefficients by 40 mel bands. */
extern const float mfcc_dct[400];
