/* Generated by model/kws/export.py. Do not edit.
   Regenerate with: python -m kws.export --checkpoint <run>/checkpoint.pt */

#pragma once

#include <stdint.h>

#define REPLAY_CLIP_COUNT   3
#define REPLAY_CLIP_SAMPLES 16000
#define REPLAY_TOTAL_SAMPLES (REPLAY_CLIP_COUNT * REPLAY_CLIP_SAMPLES)

extern const int16_t replay_samples[REPLAY_TOTAL_SAMPLES];
extern const uint8_t replay_clip_label[REPLAY_CLIP_COUNT];
extern const char *const replay_clip_name[REPLAY_CLIP_COUNT];
