"""Emit the trained model as C the firmware compiles directly.

Produces audio/kws_model.h and audio/kws_model.c holding, for every layer, an
INT8 copy with per channel requantisation parameters and an FP32 copy, plus a
descriptor table the device core walks. Both precisions are present because T4
selects precision per layer at runtime.

Also emits the MFCC tables so the device never recomputes the window, mel
filterbank, or DCT matrix, which keeps device features bit comparable with the
host reference.
"""

import numpy as np

from .features import FeatureConfig, MfccExtractor
from .quantize import (
    CONV,
    DEPTHWISE,
    FULLY_CONNECTED,
    POINTWISE,
    LayerSpec,
)

KIND_ENUM = {
    CONV: "KWS_LAYER_CONV",
    DEPTHWISE: "KWS_LAYER_DEPTHWISE",
    POINTWISE: "KWS_LAYER_POINTWISE",
    FULLY_CONNECTED: "KWS_LAYER_FULLY_CONNECTED",
}

GENERATED_NOTE = (
    "/* Generated by model/kws/export.py. Do not edit.\n"
    "   Regenerate with: python -m kws.export --checkpoint <run>/checkpoint.pt */\n"
)


def _c_array(name, values, ctype, per_line=12, fmt=None):
    if fmt is None:
        fmt = (lambda v: f"{v}") if "int" in ctype else (lambda v: f"{float(v):.8e}f")
    flat = np.asarray(values).reshape(-1)
    lines = [f"const {ctype} {name}[{flat.size}] = {{"]
    for start in range(0, flat.size, per_line):
        chunk = ", ".join(fmt(v) for v in flat[start : start + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def sparse_filterbank(filterbank: np.ndarray):
    """Triangular mel filters touch a handful of bins each, so store only those.

    Returns (start, length, weights). Every band is contiguous, which is a
    property of triangular filters on a monotonic frequency grid, and is
    asserted here because the device loop depends on it.
    """
    starts, lengths, weights = [], [], []
    for row in filterbank:
        nonzero = np.nonzero(row)[0]
        if nonzero.size == 0:
            starts.append(0)
            lengths.append(0)
            continue
        first, last = int(nonzero[0]), int(nonzero[-1])
        assert last - first + 1 == nonzero.size, "mel band is not contiguous"
        starts.append(first)
        lengths.append(last - first + 1)
        weights.extend(row[first : last + 1].tolist())
    return (
        np.asarray(starts, dtype=np.uint16),
        np.asarray(lengths, dtype=np.uint16),
        np.asarray(weights, dtype=np.float32),
    )


def emit_mfcc_tables(cfg: FeatureConfig) -> str:
    extractor = MfccExtractor(cfg)
    starts, lengths, weights = sparse_filterbank(extractor.filterbank)
    parts = [
        GENERATED_NOTE,
        '#include "mfcc_tables.h"',
        "",
        _c_array("mfcc_window", extractor.window, "float"),
        "",
        _c_array("mfcc_band_start", starts, "uint16_t", 16),
        "",
        _c_array("mfcc_band_length", lengths, "uint16_t", 16),
        "",
        _c_array("mfcc_band_weight", weights, "float"),
        "",
        _c_array("mfcc_dct", extractor.dct, "float"),
        "",
    ]
    return "\n".join(parts)


def emit_mfcc_tables_header(cfg: FeatureConfig) -> str:
    extractor = MfccExtractor(cfg)
    _, _, weights = sparse_filterbank(extractor.filterbank)
    dense = cfg.n_mel * cfg.n_bins
    return f"""{GENERATED_NOTE}
#pragma once

#include <stdint.h>

#include "mfcc_config.h"

/* Window is applied to one {cfg.frame_samples} sample frame before the transform. */
extern const float mfcc_window[{cfg.frame_samples}];

/* Mel filterbank in sparse form. A triangular filter is non zero over only a
   few neighbouring bins, {weights.size} across all {cfg.n_mel} bands against
   {dense} for the dense matrix, so the sparse form is both far smaller in flash
   and far cheaper per frame. Each band covers a contiguous run of bins. */
#define MFCC_BAND_WEIGHTS {weights.size}
extern const uint16_t mfcc_band_start[{cfg.n_mel}];
extern const uint16_t mfcc_band_length[{cfg.n_mel}];
extern const float    mfcc_band_weight[MFCC_BAND_WEIGHTS];

/* Row major, {cfg.n_mfcc} coefficients by {cfg.n_mel} mel bands. */
extern const float mfcc_dct[{cfg.n_mfcc * cfg.n_mel}];
"""


def emit_model_header(layers, labels, cfg: FeatureConfig, channels: int) -> str:
    label_list = ", ".join(f'"{name}"' for name in labels)
    return f"""{GENERATED_NOTE}
#pragma once

#include <stdint.h>

#include "kws_layer.h"

#define KWS_NUM_LAYERS      {len(layers)}
#define KWS_NUM_CLASSES     {len(labels)}
#define KWS_INPUT_FRAMES    {cfg.n_frames}
#define KWS_INPUT_MFCC      {cfg.n_mfcc}
#define KWS_MODEL_CHANNELS  {channels}

/* Largest activation tensor in elements, sizes the two ping pong arenas. */
#define KWS_MAX_TENSOR_ELEMS {_max_tensor(layers)}

/* Folded accumulator slots the inference core needs, one per output channel of
   every layer that folds its bias. Depthwise layers keep the plain path and
   take none. Checked against the static store by _Static_assert in kws_infer.c,
   so a wider model fails the build rather than overflowing at run time. */
#define KWS_FOLDED_SLOTS_REQUIRED {_folded_slots(layers)}

extern const kws_layer_t kws_layers[KWS_NUM_LAYERS];
extern const char *const kws_labels[KWS_NUM_CLASSES];

/* Quantisation of the feature grid handed to layer 0. */
extern const float   kws_input_scale;
extern const int32_t kws_input_zero_point;

/* Per coefficient feature standardisation, applied before quantisation. */
extern const float kws_feature_mean[KWS_INPUT_MFCC];
extern const float kws_feature_std[KWS_INPUT_MFCC];
"""


def _folded_slots(layers):
    """Slots fold_bias_tables consumes: one per output channel, depthwise excepted.

    Mirrors the loop in KWS_TRON/audio/kws_infer.c. The two must agree, which is
    what the _Static_assert on the device side enforces.
    """
    return sum(int(layer.out_shape[2]) for layer in layers
               if layer.kind != DEPTHWISE)


def _max_tensor(layers):
    biggest = 0
    for layer in layers:
        for shape in (layer.in_shape, layer.out_shape):
            biggest = max(biggest, int(np.prod(shape)))
    return biggest


def emit_model_source(layers, labels, cfg, input_quant, mean, std) -> str:
    blocks = [GENERATED_NOTE, '#include "kws_model.h"', ""]

    for index, layer in enumerate(layers):
        prefix = f"layer{index}_{layer.name}"
        blocks.append(_c_array(f"{prefix}_w8", layer.weight_int8, "int8_t", 16))
        blocks.append("")
        blocks.append(_c_array(f"{prefix}_b32", layer.bias_int32, "int32_t", 8))
        blocks.append("")
        blocks.append(_c_array(f"{prefix}_mult", layer.multiplier, "int32_t", 8))
        blocks.append("")
        blocks.append(_c_array(f"{prefix}_shift", layer.shift, "int32_t", 12))
        blocks.append("")
        blocks.append(_c_array(f"{prefix}_wf", layer.weight_fp32, "float", 8))
        blocks.append("")
        blocks.append(_c_array(f"{prefix}_bf", layer.bias_fp32, "float", 8))
        blocks.append("")

    rows = []
    for index, layer in enumerate(layers):
        prefix = f"layer{index}_{layer.name}"
        in_h, in_w, in_c = layer.in_shape
        out_h, out_w, out_c = layer.out_shape
        rows.append(
            f"""    {{
        .name            = "{layer.name}",
        .kind            = {KIND_ENUM[layer.kind]},
        .relu            = {1 if layer.relu else 0},
        .in_h = {in_h}, .in_w = {in_w}, .in_c = {in_c},
        .out_h = {out_h}, .out_w = {out_w}, .out_c = {out_c},
        .kernel_h = {layer.kernel[0]}, .kernel_w = {layer.kernel[1]},
        .stride_h = {layer.stride[0]}, .stride_w = {layer.stride[1]},
        .pad_h = {layer.padding[0]}, .pad_w = {layer.padding[1]},
        .weight_int8     = {prefix}_w8,
        .bias_int32      = {prefix}_b32,
        .multiplier      = {prefix}_mult,
        .shift           = {prefix}_shift,
        .weight_fp32     = {prefix}_wf,
        .bias_fp32       = {prefix}_bf,
        .input_offset    = {-layer.input_quant.zero_point},
        .output_offset   = {layer.output_quant.zero_point},
        .input_scale     = {layer.input_quant.scale:.8e}f,
        .output_scale    = {layer.output_quant.scale:.8e}f,
        .activation_min  = {layer.activation_min},
        .activation_max  = {layer.activation_max},
    }},"""
        )

    blocks.append("const kws_layer_t kws_layers[KWS_NUM_LAYERS] = {")
    blocks.extend(rows)
    blocks.append("};")
    blocks.append("")
    label_entries = ", ".join(f'"{name}"' for name in labels)
    blocks.append(
        f"const char *const kws_labels[KWS_NUM_CLASSES] = {{ {label_entries} }};"
    )
    blocks.append("")
    blocks.append(f"const float   kws_input_scale = {input_quant.scale:.8e}f;")
    blocks.append(f"const int32_t kws_input_zero_point = {input_quant.zero_point};")
    blocks.append("")
    blocks.append(_c_array("kws_feature_mean", mean.reshape(-1), "float", 8))
    blocks.append("")
    blocks.append(_c_array("kws_feature_std", std.reshape(-1), "float", 8))
    blocks.append("")
    return "\n".join(blocks)


def emit_replay_data(clips, labels, label_names, cfg: FeatureConfig) -> str:
    """Emit waveform clips as int16 PCM for the timer paced DMA replay source.

    These stand in for a live sensor. The DMA path, the half transfer
    interrupt, and the event flag handoff are identical to the microphone case,
    only the data origin differs. See docs/signal_source.md.
    """
    samples = np.concatenate(
        [np.clip(np.round(clip * 32767.0), -32768, 32767) for clip in clips]
    ).astype(np.int16)
    parts = [
        GENERATED_NOTE,
        '#include "replay_data.h"',
        "",
        _c_array("replay_samples", samples, "int16_t", 16),
        "",
        _c_array("replay_clip_label", labels, "uint8_t", 16),
        "",
    ]
    names = ", ".join(f'"{label_names[i]}"' for i in labels)
    parts.append(f"const char *const replay_clip_name[{len(labels)}] = {{ {names} }};")
    parts.append("")
    return "\n".join(parts)


def emit_replay_header(n_clips: int, cfg: FeatureConfig) -> str:
    return f"""{GENERATED_NOTE}
#pragma once

#include <stdint.h>

#define REPLAY_CLIP_COUNT   {n_clips}
#define REPLAY_CLIP_SAMPLES {cfg.clip_samples}
#define REPLAY_TOTAL_SAMPLES (REPLAY_CLIP_COUNT * REPLAY_CLIP_SAMPLES)

extern const int16_t replay_samples[REPLAY_TOTAL_SAMPLES];
extern const uint8_t replay_clip_label[REPLAY_CLIP_COUNT];
extern const char *const replay_clip_name[REPLAY_CLIP_COUNT];
"""


def emit_eval_set(features_q, labels, cfg: FeatureConfig) -> str:
    """Quantised feature grids with ground truth, for on device accuracy runs."""
    parts = [
        GENERATED_NOTE,
        '#include "eval_set.h"',
        "",
        _c_array("eval_features", features_q, "int8_t", 16),
        "",
        _c_array("eval_labels", labels, "uint8_t", 16),
        "",
    ]
    return "\n".join(parts)


def emit_eval_header(n_samples: int, cfg: FeatureConfig) -> str:
    return f"""{GENERATED_NOTE}
#pragma once

#include <stdint.h>

#define EVAL_SAMPLE_COUNT  {n_samples}
#define EVAL_FRAME_COUNT   {cfg.n_frames}
#define EVAL_MFCC_COUNT    {cfg.n_mfcc}
#define EVAL_ELEMS_PER_SAMPLE (EVAL_FRAME_COUNT * EVAL_MFCC_COUNT)

/* Row major, EVAL_SAMPLE_COUNT by EVAL_ELEMS_PER_SAMPLE, already quantised
   with kws_input_scale and kws_input_zero_point. */
extern const int8_t  eval_features[EVAL_SAMPLE_COUNT * EVAL_ELEMS_PER_SAMPLE];
extern const uint8_t eval_labels[EVAL_SAMPLE_COUNT];
"""


def model_size_report(layers) -> dict:
    int8_bytes = sum(layer.weight_int8.size + layer.bias_int32.size * 4 for layer in layers)
    fp32_bytes = sum(
        (layer.weight_fp32.size + layer.bias_fp32.size) * 4 for layer in layers
    )
    requant = sum(layer.multiplier.size * 8 for layer in layers)
    return {
        "int8_bytes": int(int8_bytes),
        "fp32_bytes": int(fp32_bytes),
        "requant_bytes": int(requant),
        "total_bytes": int(int8_bytes + fp32_bytes + requant),
    }


def main():
    import argparse
    import json
    from datetime import datetime
    from pathlib import Path

    import torch

    from .convert import assign_quantisation, calibrate, flatten_graph, run_reference
    from .dataset import LABELS
    from .model import DSCNN
    from .quantize import activation_quant

    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--out-dir", default="KWS_TRON/audio")
    parser.add_argument("--cache", default="model/datasets/cache")
    parser.add_argument(
        "--replay-clips", type=int, default=None,
        help="truncate the replay corpus, default is every clip make_replay built",
    )
    parser.add_argument("--eval-samples", type=int, default=150)
    parser.add_argument("--verify-samples", type=int, default=24)
    parser.add_argument("--calib-samples", type=int, default=512)
    args = parser.parse_args()

    checkpoint = torch.load(args.checkpoint, map_location="cpu", weights_only=False)
    cfg = FeatureConfig(
        **{
            k: v
            for k, v in checkpoint["config"].items()
            if k in FeatureConfig.__dataclass_fields__
        }
    )
    model = DSCNN(len(checkpoint["labels"]), checkpoint["channels"], checkpoint["blocks"], cfg)
    model.load_state_dict(checkpoint["state_dict"])
    model.eval()

    mean = np.asarray(checkpoint["norm_mean"], dtype=np.float32)
    std = np.asarray(checkpoint["norm_std"], dtype=np.float32)

    cache_dir = repo_root / args.cache
    blob = np.load(next(cache_dir.glob("features_*.npz")))
    train_x = ((blob["train_x"] - mean) / std).astype(np.float32)
    test_x = ((blob["test_x"] - mean) / std).astype(np.float32)
    test_y = blob["test_y"]

    calib = train_x[: args.calib_samples]
    layers = flatten_graph(model, cfg)
    ranges = calibrate(model, calib, torch.device("cpu"))
    input_quant = activation_quant(float(calib.min()), float(calib.max()))
    layers = assign_quantisation(layers, ranges, (float(calib.min()), float(calib.max())))

    # Verify the quantised graph against the float model before emitting it.
    subset = min(args.verify_samples, len(test_x))
    agree_int8 = 0
    with torch.no_grad():
        float_pred = model(torch.from_numpy(test_x[:subset]).unsqueeze(1)).argmax(1).numpy()
    for i in range(subset):
        logits = run_reference(layers, test_x[i], input_quant, ["int8"] * len(layers))
        agree_int8 += int(logits.argmax() == float_pred[i])
    agreement = agree_int8 / subset
    print(f"int8 reference agrees with float model on {agree_int8}/{subset} samples")

    out_dir = repo_root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "kws_model.h").write_text(
        emit_model_header(layers, checkpoint["labels"], cfg, checkpoint["channels"])
    )
    (out_dir / "kws_model.c").write_text(
        emit_model_source(layers, checkpoint["labels"], cfg, input_quant, mean, std)
    )
    (out_dir / "mfcc_tables.h").write_text(emit_mfcc_tables_header(cfg))
    (out_dir / "mfcc_tables.c").write_text(emit_mfcc_tables(cfg))

    eval_n = min(args.eval_samples, len(test_x))
    stride = max(1, len(test_x) // eval_n)
    picks = np.arange(0, len(test_x), stride)[:eval_n]
    eval_q = np.stack([input_quant.quantise(test_x[i]) for i in picks])
    (out_dir / "eval_set.h").write_text(emit_eval_header(eval_n, cfg))
    (out_dir / "eval_set.c").write_text(
        emit_eval_set(eval_q, test_y[picks].astype(np.uint8), cfg)
    )

    # Prefer the stratified corpus from make_replay.py, which alternates
    # keyword and silence so the voice activity gate is exercised in both
    # directions. Fall back to the raw clips in the feature cache, which are in
    # bucket order and therefore all one word.
    replay_path = cache_dir / "replay_clips.npz"
    if replay_path.exists():
        clips = np.load(replay_path)
        raw, raw_y = clips["waves"], clips["labels"]
        print(f"replay corpus from {replay_path.name}, {len(raw)} clips")
    elif "test_raw" in blob:
        raw, raw_y = blob["test_raw"], blob["test_raw_y"]
        print("replay corpus from the feature cache, unstratified")
    else:
        raw = None

    if raw is not None:
        # The stratified corpus is built as a whole: alternating keyword and
        # silence is the property that makes the gate observable, and half a
        # corpus is not half as useful, it is a different experiment. So it is
        # used entire unless a count is passed. A default that disagreed with
        # make_replay's is what previously let an export silently emit three
        # clips from a six clip corpus and change what the firmware replays.
        take = len(raw) if args.replay_clips is None else min(args.replay_clips, len(raw))
        if take != len(raw):
            print(f"WARNING replay corpus truncated to {take} of {len(raw)} clips")
        (out_dir / "replay_data.h").write_text(emit_replay_header(take, cfg))
        (out_dir / "replay_data.c").write_text(
            emit_replay_data(
                [raw[i] for i in range(take)],
                raw_y[:take].astype(np.uint8),
                checkpoint["labels"],
                cfg,
            )
        )

    sizes = model_size_report(layers)
    sizes["eval_bytes"] = int(eval_q.size)
    print("flash budget:")
    for key, value in sizes.items():
        print(f"  {key:16} {value / 1024:8.1f} KB")

    stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    run_dir = repo_root / "experiments" / f"{stamp}_model-export"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "results.md").write_text(
        f"# Model export\n\nCheckpoint `{args.checkpoint}`.\n\n"
        f"The int8 reference agrees with the float model on {agree_int8}/{subset} "
        f"verification samples ({agreement:.3f}).\n\n"
        + "\n".join(f"- {k}: {v / 1024:.1f} KB" for k, v in sizes.items())
        + "\n"
    )
    (run_dir / "config.json").write_text(json.dumps({"args": vars(args), "sizes": sizes}, indent=2))
    print(f"export recorded in {run_dir}")


if __name__ == "__main__":
    main()
