/*
 *	power_save.c (STM32Cube)
 *	Power-Saving Function
 *
 *	Project modification to the vendored BSP. The shipped file left both hooks
 *	empty, so the idle task spun at the full clock and no amount of gating work
 *	upstream could reduce power. Documented in docs/power.md.
 */

#include <sys/machine.h>
#include <tk/tkernel.h>

#ifdef MTKBSP_STM32CUBE

#include <stdint.h>

#include "app_config.h"

/* DWT cycle counter, read directly so this file needs no CMSIS include. */
#define DWT_CYCCNT (*(volatile uint32_t *)0xE0001004UL)

/* Idle residency. The 32 bit counter wraps about every 17 seconds at 250 MHz,
   so only the per interval delta is taken from it and the total is kept in 64
   bits. This is the measured quantity behind the power claim: the fraction of
   wall time the core spent asleep rather than spinning. */
static uint64_t idle_cycles;
static uint32_t idle_entries;

uint64_t bsp_idle_cycles(void)  { return idle_cycles; }
uint32_t bsp_idle_entries(void) { return idle_entries; }

/*
 * Switch to power-saving mode
 *
 * Called from the dispatcher with BASEPRI already raised to mask external
 * interrupts. A bare WFI there would never wake, because the interrupts that
 * would end the idle period are exactly the ones BASEPRI is masking. The
 * sequence below is the standard way out: PRIMASK blocks the interrupt from
 * being taken while BASEPRI is dropped, so the pending interrupt still counts
 * as a wake up event, and the dispatcher's masking is restored before the
 * interrupt is allowed through.
 */
EXPORT void low_pow( void )
{
	uint32_t entered = DWT_CYCCNT;

#if KWS_IDLE_SLEEP
	uint32_t saved_basepri;

	/* BASEPRI is dropped around the WFI because a wake up event is only
	   generated by an exception that would preempt the current execution
	   priority, and BASEPRI is part of that priority: the very interrupts that
	   should end the idle period are the ones the dispatcher has masked.
	   PRIMASK is deliberately NOT used here. Holding it across the WFI is the
	   textbook sequence but it leaves no path out if the wake up is missed,
	   whereas simply reopening BASEPRI cannot deadlock: an interrupt arriving
	   before the WFI is taken immediately and the next one ends the sleep. */
	__asm__ volatile (
		"mrs	%0, basepri	\n"
		"mov	r1, #0		\n"
		"msr	basepri, r1	\n"
		"dsb			\n"
		"isb			\n"
		"wfi			\n"
		"msr	basepri, %0	\n"
		: "=&r" (saved_basepri)
		:
		: "r1", "memory"
	);
#endif

	idle_cycles += (uint32_t)(DWT_CYCCNT - entered);
	idle_entries++;
}

/*
 * Move to suspend mode
 */
EXPORT void off_pow( void )
{
}

#endif /* MTKBSP_STM32CUBE */
